FROM alpine:3.2
RUN apk update && apk add --no-progress bash gcc g++ make perl fontconfig-dev libx11-dev libxmu-dev libxaw-dev
# clean up ???
# RUN apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
