FROM centos:7
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
RUN yum install -y centos-release-scl
RUN yum install -y devtoolset-9
RUN yum install -y fontconfig-devel libX11-devel  libXmu-devel libXaw-devel
RUN yum clean all
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
