FROM centos:7
RUN yum update -y && \
    yum install -y centos-release-scl && \
    yum install -y devtoolset-9 fontconfig-devel libX11-devel libXmu-devel libXaw-devel && \
    yum clean all
COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
